# -*- coding: utf-8 -*-
"""The documentation's format, held as code.

    hpprime docs            check, then regenerate the group pages and the
                            index from the entries and the list of names
    hpprime docs --check    change nothing; exit 1 if anything breaks the
                            format or a generated page is out of date

docs/format.md states the format for a reader. This module holds the pages to
it: the command entries under docs/commands/<group>/, the facts in
docs/topics/, the list of every PPL name in docs/commands/names.tsv, and the
pages generated from them. It also runs the examples of every command the
interpreter implements, because an entry that says it runs on the PC makes a
claim a test can check.

Nothing here judges whether a label is true: that is what the evidence behind
it is for. It judges that every claim carries one.
"""
from __future__ import unicode_literals
import io, os, re, sys
from collections import OrderedDict

from hpkit import interp
from hpkit import names as namelist

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LABELS = ('G2', 'emulator', 'HP help', 'unverified')     # strongest first
KINDS = ('rule', 'refuted hypothesis')
FIELDS = ('Syntax', 'Group', 'Runs on the PC')
SECTIONS = ('Examples', 'Behaviour', 'Models get wrong', 'Related')
REQUIRED = ('Examples', 'Behaviour')
# The result of an example that has nothing to record: the command's result
# is the screen, or it stops the program, or it is a declaration rather than
# a call. Nothing runs one of these.
NO_VALUE = '*no value*'
TOLERANCE = 2e-4        # HP prints rounded results: MIN(8/3,11/4) -> 2.6667

# The layer built on top of the documentation. The documentation never points
# at it, so that it stands on its own and could be split out.
ABOVE = re.compile(r'(?<![\w-])(kit/|AGENTS\.md|SKILL\.md|docs/ai/|\.planning)')

GENERATED = ('<!-- Generated by `hpprime docs` from the entries in %s. '
             'Edit those, not this page. -->')

LINK = re.compile(r'\[([^\]]*)\]\(([^)\s]+)\)')
PARENS = re.compile(r'\(([^()]*)\)')
LABEL_WORD = re.compile(r'(?<!\w)(G2|emulator|HP help|unverified)(?!\w)')
FACT_ID = re.compile(r'^[a-z][a-z0-9]*(\.[a-z0-9][a-z0-9-]*)+$')

# Two names on HP's list can differ only in case and share a group: ROOT the
# app function against Root the app variable, and four more pairs. This
# filesystem cannot hold ROOT.md and Root.md in one folder, so the variable's
# entry keeps its real name in the title and takes this suffix on the file.
# The suffix is declared once here rather than invented per file, and nothing
# else changes: the index and the group pages already link with the title as
# the text and the file name as the path.
NAME_SUFFIX = '-var'
ANCHOR = re.compile(r'^<a name="([^"]+)"></a>\s*$')
SEPARATOR = re.compile(r'^:?-{3,}:?$')
EVIDENCE = '**Evidence.**'

# How the kinds that get no entry of their own are named in the index.
PLURALS = OrderedDict([('cas', 'CAS names'), ('keyword', 'keywords'),
                       ('operator', 'operators')])


class Problem(object):
    """One thing wrong, compiler-shaped: `path:line: message`."""

    def __init__(self, root, path, line, message):
        self.path = _rel(root, path)
        self.line = line
        self.message = message

    def __str__(self):
        return '%s:%d: %s' % (self.path, self.line, self.message)


class Example(object):
    def __init__(self, line, call, result, label, target, no_value=False):
        self.line = line
        self.call = call
        self.result = result        # PPL as displayed, or None
        self.label = label
        self.target = target
        # True when the result is NO_VALUE: there is nothing to compare, so
        # neither the interpreter nor a batch on the emulator runs it, and
        # the entry says in words why there is nothing to record.
        self.no_value = no_value


class Entry(object):
    def __init__(self, path, text):
        self.path = path
        self.text = text
        self.folder = os.path.basename(os.path.dirname(path))
        self.stem = os.path.splitext(os.path.basename(path))[0]
        self.name = None
        self.summary = ''
        self.syntax = []
        self.group = None
        self.runs = False
        self.examples = []

    @property
    def weakest(self):
        """The weakest label among the examples, or None without any."""
        if not self.examples:
            return None
        return max((ex.label for ex in self.examples), key=LABELS.index)


class Fact(object):
    def __init__(self, path, ident, line):
        self.path = path
        self.ident = ident
        self.line = line
        self.kind = None
        self.label = None


# ------------------------------------------------------------------ reading

def _rel(root, path):
    return os.path.relpath(path, root).replace(os.sep, '/')


def _list_path(root):
    return os.path.join(root, 'docs', 'commands', 'names.tsv')


def _skip_blank(lines, i):
    while i < len(lines) and not lines[i].strip():
        i += 1
    return i


def cells(line):
    """The cells of a Markdown table row. A | inside backticks belongs to
    the cell."""
    line = line.strip()
    if line.startswith('|'):
        line = line[1:]
    if line.endswith('|'):
        line = line[:-1]
    out, cur, code = [], '', False
    for c in line:
        if c == '`':
            code = not code
        if c == '|' and not code:
            out.append(cur.strip())
            cur = ''
        else:
            cur += c
    out.append(cur.strip())
    return out


def _table(lines, i):
    """-> ([(index, cells)], index after it) for the table at lines[i]."""
    rows = []
    while i < len(lines) and lines[i].lstrip().startswith('|'):
        rows.append((i, cells(lines[i])))
        i += 1
    return rows, i


def _has_separator(rows):
    return len(rows) > 1 and all(SEPARATOR.match(c) for c in rows[1][1])


def _paragraphs(lines):
    """-> [(index of its first line, text)], paragraphs split on blanks."""
    out, start, cur = [], None, []
    for i, line in enumerate(list(lines) + ['']):
        if line.strip():
            if start is None:
                start = i
            cur.append(line.strip())
        elif cur:
            out.append((start, ' '.join(cur)))
            start, cur = None, []
    return out


def _label(cell):
    """-> (label, link target or None), or (None, None) if the cell is not
    exactly one label."""
    m = re.match(r'^\[([^\]]+)\]\(([^)\s]+)\)$', cell)
    text, target = (m.group(1), m.group(2)) if m else (cell, None)
    return (text, target) if text in LABELS else (None, None)


def read_entry(root, path):
    """-> (Entry, [Problem]) for one command entry."""
    problems = []

    def bad(line, message):
        problems.append(Problem(root, path, line, message))

    text = io.open(path, encoding='utf-8').read()
    e = Entry(path, text)
    lines = text.split('\n')

    i = _skip_blank(lines, 0)
    if i >= len(lines) or not lines[i].startswith('# '):
        bad(i + 1, 'an entry starts with "# NAME"')
        return e, problems
    e.name = lines[i][2:].strip()
    if e.name != e.stem and e.stem != e.name + NAME_SUFFIX:
        bad(i + 1, 'the title is "%s" but the file is %s.md: they are the '
            'same, or the file adds "%s" where two names differ only in '
            'case' % (e.name, e.stem, NAME_SUFFIX))

    i = _skip_blank(lines, i + 1)
    start = i
    while i < len(lines) and lines[i].strip() and \
            not lines[i].startswith(('|', '#')):
        i += 1
    e.summary = ' '.join(l.strip() for l in lines[start:i])
    if not e.summary:
        bad(start + 1, 'after the title comes one sentence saying what it does')
    elif not e.summary.endswith('.'):
        bad(start + 1, 'the summary is one sentence, ending in a full stop')

    i = _skip_blank(lines, i)
    rows, i = _table(lines, i)
    keys = []
    if not _has_separator(rows):
        bad(i + 1, 'after the summary comes the fields table: Syntax, '
            'Group, Runs on the PC')
    else:
        for n, row in rows[2:]:
            if len(row) != 2:
                bad(n + 1, 'a field row has two cells: the field, its value')
                continue
            key, value = row
            if key not in FIELDS:
                bad(n + 1, 'unknown field "%s": the fields are %s'
                    % (key, ', '.join(FIELDS)))
                continue
            keys.append(key)
            if key == 'Syntax':
                e.syntax.append(value)
            elif key == 'Group':
                e.group = value
                if value != e.folder:
                    bad(n + 1, 'Group is "%s" but the entry lives in %s/'
                        % (value, e.folder))
            elif value not in ('yes', 'no'):
                bad(n + 1, '"Runs on the PC" is yes or no')
            else:
                e.runs = value == 'yes'
        order = [k for j, k in enumerate(keys) if j == 0 or keys[j - 1] != k]
        if order != list(FIELDS):
            bad(rows[0][0] + 1, 'the fields are Syntax (one row per form), '
                'then Group, then Runs on the PC, each of them, in that order')

    sections = []
    for j in range(i, len(lines)):
        if lines[j].startswith('## '):
            sections.append([lines[j][3:].strip(), j, len(lines)])
        elif lines[j].startswith('# '):
            bad(j + 1, 'an entry has one title')
        elif lines[j].strip() and not sections:
            bad(j + 1, 'after the fields come the sections, "## Examples" first')
    for k in range(len(sections) - 1):
        sections[k][2] = sections[k + 1][1]
    names = [s[0] for s in sections]
    for name, j, _ in sections:
        if name not in SECTIONS:
            bad(j + 1, 'unknown section "%s": the sections are %s'
                % (name, ', '.join(SECTIONS)))
    known = [n for n in names if n in SECTIONS]
    if known != sorted(set(known), key=SECTIONS.index):
        bad(sections[0][1] + 1, 'the sections come in this order, once '
            'each: %s' % ', '.join(SECTIONS))
    for name in REQUIRED:
        if name not in names:
            bad(len(lines), 'missing section "## %s"' % name)

    for name, j, end in sections:
        body = lines[j + 1:end]
        if name == 'Examples':
            _examples(e, body, j + 1, bad)
        elif name == 'Behaviour':
            _behaviour(body, j + 1, bad)
        elif name == 'Models get wrong':
            _mistakes(body, j + 1, bad)
    return e, problems


def _examples(e, body, offset, bad):
    k = _skip_blank(body, 0)
    rows, _ = _table(body, k)
    if not _has_separator(rows) or len(rows) < 3 or \
            rows[0][1] != ['Call', 'Result', 'Known from']:
        bad(offset + k + 1, 'Examples is a table, Call | Result | Known '
            'from, with at least one row')
        return
    for idx, row in rows[2:]:
        n = offset + idx + 1
        if len(row) != 3:
            bad(n, 'an example has three cells: the call, the result, and '
                'how the result is known')
            continue
        call, result, known = row
        mc = re.match(r'^`(.+)`$', call)
        if not mc:
            bad(n, 'the call is PPL in backticks')
            continue
        no_value = result == NO_VALUE
        if result == '*error*' or no_value:
            value = None
        else:
            mr = re.match(r'^`(.*)`$', result)
            if not mr:
                bad(n, 'the result is PPL in backticks, *error*, or %s'
                    % NO_VALUE)
                continue
            value = mr.group(1)
        label, target = _label(known)
        if label is None:
            bad(n, 'every example has exactly one label: %s'
                % ', '.join(LABELS))
            continue
        e.examples.append(Example(n, mc.group(1), value, label, target,
                                  no_value))


def _behaviour(body, offset, bad):
    paragraphs = _paragraphs(body)
    if not paragraphs:
        bad(offset, 'Behaviour has at least one paragraph')
    for idx, text in paragraphs:
        if text.startswith(EVIDENCE):
            continue
        if not any(LABEL_WORD.search(inner) for inner in PARENS.findall(text)):
            bad(offset + idx + 1, 'every paragraph in Behaviour says how it '
                'is known, with a label in parentheses: (G2), (HP help)...')


def _mistakes(body, offset, bad):
    k = _skip_blank(body, 0)
    rows, _ = _table(body, k)
    if not _has_separator(rows) or len(rows) < 3 or \
            rows[0][1] != ['They write', 'What happens', 'Seen in']:
        bad(offset + k + 1, 'Models get wrong is a table, They write | What '
            'happens | Seen in, with at least one row')
        return
    for idx, row in rows[2:]:
        if len(row) != 3 or not row[2]:
            bad(offset + idx + 1, 'a mistake models make needs where it '
                'was seen')


def read_topic(root, path):
    """-> ([Fact], [Problem]) for one topic page."""
    problems, facts = [], []

    def bad(line, message):
        problems.append(Problem(root, path, line, message))

    lines = io.open(path, encoding='utf-8').read().split('\n')
    topic = os.path.splitext(os.path.basename(path))[0]
    anchors = [(n, m.group(1)) for n, m in
               ((n, ANCHOR.match(l)) for n, l in enumerate(lines)) if m]
    for a, (n, ident) in enumerate(anchors):
        end = anchors[a + 1][0] if a + 1 < len(anchors) else len(lines)
        block = lines[n:end]
        f = Fact(path, ident, n + 1)
        facts.append(f)
        if not FACT_ID.match(ident) or not ident.startswith(topic + '.'):
            bad(n + 1, 'a fact identifier is the topic, a dot and a slug, '
                'as in %s.something' % topic)
        k = _skip_blank(block, 1)
        if k >= len(block) or not block[k].startswith('## '):
            bad(n + 1, 'the anchor is followed by a "## " heading that '
                'states the fact')
            continue
        k = _skip_blank(block, k + 1)
        rows, k = _table(block, k)
        fields = OrderedDict()
        for idx, row in rows[2:] if _has_separator(rows) else []:
            if len(row) == 2:
                fields[row[0]] = (n + idx + 1, row[1])
        if list(fields) != ['Identifier', 'Kind', 'Known from']:
            bad(n + 1, 'a fact has the fields Identifier, Kind and Known '
                'from, in that order')
        line, value = fields.get('Identifier', (n + 1, ''))
        if value != '`%s`' % ident:
            bad(line, 'the Identifier field repeats the anchor: `%s`' % ident)
        line, value = fields.get('Kind', (n + 1, ''))
        f.kind = value
        if value not in KINDS:
            bad(line, 'Kind is rule or refuted hypothesis')
        line, value = fields.get('Known from', (n + 1, ''))
        f.label = _label(value)[0]
        if f.label is None:
            bad(line, 'Known from is one label: %s' % ', '.join(LABELS))
        texts = [t for _, t in _paragraphs(block[k:])]
        if not [t for t in texts if not t.startswith(EVIDENCE)]:
            bad(n + 1, 'a fact is stated in a paragraph before its evidence')
        if not [t for t in texts if t.startswith(EVIDENCE)]:
            bad(n + 1, 'a fact ends with a paragraph that begins %s'
                % EVIDENCE)
    return facts, problems


def load(root=ROOT):
    """-> (entries, facts, problems) for the documentation under root."""
    entries, facts, problems = [], [], []
    commands = os.path.join(root, 'docs', 'commands')
    if os.path.isdir(commands):
        for group in sorted(os.listdir(commands)):
            folder = os.path.join(commands, group)
            if not os.path.isdir(folder):
                continue
            for name in sorted(os.listdir(folder)):
                if name.endswith('.md'):
                    e, p = read_entry(root, os.path.join(folder, name))
                    entries.append(e)
                    problems += p
    topics = os.path.join(root, 'docs', 'topics')
    if os.path.isdir(topics):
        for name in sorted(os.listdir(topics)):
            if name.endswith('.md'):
                f, p = read_topic(root, os.path.join(topics, name))
                facts += f
                problems += p
    return entries, facts, problems


# ----------------------------------------------------------------- checking

def _layer_files(root):
    """Every page of the documentation this module is responsible for."""
    out = []
    for sub in ('commands', 'topics'):
        base = os.path.join(root, 'docs', sub)
        for folder, dirs, files in os.walk(base):
            dirs.sort()
            out += [os.path.join(folder, f) for f in sorted(files)
                    if f.endswith('.md')]
    fmt = os.path.join(root, 'docs', 'format.md')
    if os.path.isfile(fmt):
        out.append(fmt)
    return out


def _key(path):
    return os.path.normcase(os.path.abspath(path))


def _inside(path, folder):
    return _key(path).startswith(_key(folder) + os.sep)


def cross_check(root, entries, facts):
    """Names and identifiers unique, links resolving, and nothing pointing at
    the layer built on the documentation."""
    problems = []

    def bad(path, line, message):
        problems.append(Problem(root, path, line, message))

    first = {}
    for e in entries:
        if e.name in first:
            bad(e.path, 1, 'the name %s is already an entry: %s'
                % (e.name, _rel(root, first[e.name])))
        elif e.name:
            first[e.name] = e.path
    seen = {}
    for f in facts:
        if f.ident in seen:
            bad(f.path, f.line, 'the identifier %s is already used at %s:%d'
                % (f.ident, _rel(root, seen[f.ident].path),
                   seen[f.ident].line))
        else:
            seen[f.ident] = f

    known = set((_key(f.path), f.ident) for f in facts)
    topics = os.path.join(root, 'docs', 'topics')
    for path in _layer_files(root):
        fence = False
        for n, line in enumerate(io.open(path, encoding='utf-8')
                                 .read().split('\n'), 1):
            m = ABOVE.search(line)
            if m:
                bad(path, n, 'the documentation must not point at the layer '
                    'built on it: %s' % m.group(1))
            if line.startswith('```'):
                fence = not fence
            if fence:
                continue
            for lm in LINK.finditer(line):
                target = lm.group(2)
                if target.startswith(('http://', 'https://', 'mailto:')):
                    continue
                file_part, _, anchor = target.partition('#')
                dest = (os.path.normpath(os.path.join(os.path.dirname(path),
                                                      file_part))
                        if file_part else path)
                if not os.path.exists(dest):
                    bad(path, n, 'the link %s goes nowhere' % target)
                elif anchor and '.' in anchor and _inside(dest, topics) \
                        and (_key(dest), anchor) not in known:
                    bad(path, n, 'the link %s names no fact' % target)
    return problems


def list_check(root, entries):
    """The list of names well formed, every entry's name on it, and every
    entry in the folder of the group the list gives it."""
    path = _list_path(root)
    rows, bad = namelist.read(path)
    problems = [Problem(root, path, n, m) for n, m in bad]
    by = {}
    for r in rows:
        by.setdefault(r.name, r)
    for e in entries:
        if not e.name or not rows:
            continue
        r = by.get(e.name)
        if r is None:
            problems.append(Problem(root, e.path, 1, '%s is not on the list '
                                    'of names, docs/commands/names.tsv'
                                    % e.name))
        elif r.group != e.folder:
            problems.append(Problem(root, e.path, 1, 'the list files %s under '
                                    '%s, but the entry lives in %s/'
                                    % (e.name, r.group or 'no group',
                                       e.folder)))
    return problems


# ----------------------------------------------------------------- examples

def parse_result(text):
    """A result as the calculator prints it, as a Python value.

    Lists come as {a,b} and matrices as [[a,b],[c,d]]; both become nested
    lists, because that is what the interpreter returns for either. HP also
    prints a plain vector space-separated -- SIZE of a matrix answers [2 3] --
    so whitespace separates too when there is no comma.

    The calculator writes a negative with U+2212, the mathematical minus
    sign, and an entry is written with the hyphen anybody can type, so the
    two are the same sign here: ppl.minus-sign, measured on the Virtual
    Calculator 2.4, build 2025-09-15."""
    text = text.strip().replace('−', '-')
    if len(text) > 1 and text[0] in '{[' and text[-1] in '}]':
        inner = text[1:-1].replace('] [', '],[')
        out, depth, cur = [], 0, ''
        commas = False
        for c in inner:
            if c in '{[':
                depth += 1
            elif c in ']}':
                depth -= 1
            elif c == ',' and depth == 0:
                commas = True
        sep = ',' if commas else ' '
        for c in inner:
            if c in '{[':
                depth += 1
            elif c in ']}':
                depth -= 1
            if c == sep and depth == 0:
                if cur.strip():
                    out.append(parse_result(cur))
                cur = ''
            else:
                cur += c
        if cur.strip():
            out.append(parse_result(cur))
        return out
    if len(text) > 1 and text[0] == '"' and text[-1] == '"':
        return text[1:-1]
    try:
        return float(text)
    except ValueError:
        return text


def same(got, want):
    """Does what the interpreter answered match a printed result?"""
    if isinstance(got, interp.Matrix):
        got = [list(r) for r in got.rows]
    if isinstance(want, list):
        return (isinstance(got, list) and len(got) == len(want)
                and all(same(g, w) for g, w in zip(got, want)))
    if isinstance(want, float):
        return (isinstance(got, float)
                and abs(got - want) <= TOLERANCE * max(1.0, abs(want)))
    return got == want


def show(v):
    """A value the way the calculator would print it, for messages."""
    if isinstance(v, interp.Matrix):
        v = [list(r) for r in v.rows]
        return '[%s]' % ','.join('[%s]' % ','.join(show(x) for x in r)
                                 for r in v)
    if isinstance(v, list):
        return '{%s}' % ','.join(show(x) for x in v)
    if isinstance(v, float):
        return '%d' % v if v == int(v) and abs(v) < 1e15 else repr(round(v, 11))
    if isinstance(v, str):
        return '"%s"' % v
    return repr(v)


def evaluate(call):
    """-> ('value', v), ('error', message) or ('uncovered', why).

    A call with a `;` is the body of a function; without one it is an
    expression. What the interpreter cannot read is uncovered, never an
    error: an error here means the calculator's kind of refusal."""
    body = call if ';' in call else 'RETURN %s;' % call
    m = interp.Machine()
    try:
        m.load('EXPORT T()\nBEGIN\n  %s\nEND;' % body)
    except Exception as e:
        return 'uncovered', 'the interpreter could not read it: %s' % e
    try:
        return 'value', m.call('T')
    except interp.PPLError as e:
        return 'error', '%s' % e
    except interp.Unsupported as e:
        return 'uncovered', '%s' % e
    except Exception as e:                  # a gap, not a verdict
        return 'uncovered', '%s: %s' % (type(e).__name__, e)


def run_examples(root, entries):
    """-> (problems, notes, how many ran) for every entry that says it runs
    on the PC. A different answer is a problem; an example the interpreter
    does not cover is a note, because the interpreter is a subset and says
    so rather than guessing."""
    problems, notes, ran = [], [], 0
    for e in entries:
        if not e.runs:
            continue
        for ex in e.examples:
            if ex.no_value:
                continue        # nothing to compare it with
            kind, got = evaluate(ex.call)
            if kind == 'uncovered':
                notes.append(Problem(root, e.path, ex.line, 'not covered by '
                                     'the interpreter, so not checked: %s'
                                     % got))
                continue
            ran += 1
            if ex.result is None:
                if kind == 'value':
                    problems.append(Problem(
                        root, e.path, ex.line, 'the interpreter answers %s '
                        'where the entry says error' % show(got)))
                continue
            if kind == 'error':
                problems.append(Problem(
                    root, e.path, ex.line, 'the interpreter raises (%s) where '
                    'the entry says %s' % (got, ex.result)))
            elif not same(got, parse_result(ex.result)):
                problems.append(Problem(
                    root, e.path, ex.line, 'the interpreter answers %s; the '
                    'entry says %s' % (show(got), ex.result)))
    return problems, notes, ran


# --------------------------------------------------------------- generating

def _shift(text):
    """Headings one level down, so an entry sits under its group's title."""
    out, fence = [], False
    for line in text.split('\n'):
        if line.startswith('```'):
            fence = not fence
        if not fence and re.match(r'^#{1,5} ', line):
            line = '#' + line
        out.append(line)
    return '\n'.join(out)


def _rebase(text, src, dst):
    """Relative links written from folder src, rewritten for folder dst."""
    def fix(m):
        label, target = m.group(1), m.group(2)
        if target.startswith(('http://', 'https://', 'mailto:', '#')):
            return m.group(0)
        file_part, sep, anchor = target.partition('#')
        dest = os.path.normpath(os.path.join(src, file_part))
        new = os.path.relpath(dest, dst).replace(os.sep, '/')
        return '[%s](%s%s%s)' % (label, new, sep, anchor)
    return LINK.sub(fix, text)


def _index(root, entries):
    """The index: every documented name on the list, with its entry when it
    has one, and any entry that is not on the list, so nothing is hidden."""
    rows = namelist.read(_list_path(root))[0]
    by_entry = OrderedDict((e.name, e) for e in entries if e.name)
    documented = [r for r in rows if r.documented]
    covered = sum(1 for r in documented if r.name in by_entry)
    lines = ['# Commands', '', GENERATED % '`docs/commands/`', '',
             'Every name PPL has, from [the list of names](names.tsv): what '
             'kind of name it is and where HP files it, and, for the ones '
             'with an entry, what it does and the weakest label among its '
             'examples. How an entry is written: [format.md](../format.md).',
             '']
    if rows:
        rest = [(PLURALS[k], sum(1 for r in rows if r.kind == k))
                for k in PLURALS]
        rest = ['%d %s' % (n, what) for what, n in rest if n]
        lines += ['%d of %d names have an entry so far. The list also holds '
                  '%s, which are not documented one by one.'
                  % (covered, len(documented),
                     ', '.join(rest[:-1]) + ' and ' + rest[-1]
                     if len(rest) > 1 else ''.join(rest)), '']
    lines += ['| Name | Kind | Group | What it does | Weakest evidence |',
              '|---|---|---|---|---|']

    def linked(e, kind):
        return '| [%s](%s/%s.md) | %s | [%s](%s.md) | %s | %s |' % (
            e.name, e.folder, e.stem, kind, e.folder, e.folder, e.summary,
            e.weakest or 'no examples')

    listed = set()
    for r in sorted(documented, key=lambda r: (r.name.lower(), r.name)):
        listed.add(r.name)
        e = by_entry.get(r.name)
        lines.append(linked(e, r.kind) if e else
                     '| `%s` | %s | %s | no entry yet | |'
                     % (r.name, r.kind, r.group or '-'))
    for e in sorted(entries, key=lambda e: e.name or ''):
        if e.name and e.name not in listed:
            lines.append(linked(e, 'not on the list'))
    return '\n'.join(lines) + '\n'


def generated(root, entries):
    """-> OrderedDict {path: text}: every page produced from the entries."""
    commands = os.path.join(root, 'docs', 'commands')
    groups = OrderedDict()
    for e in sorted(entries, key=lambda e: (e.folder, e.name or '')):
        groups.setdefault(e.folder, []).append(e)
    out = OrderedDict()
    for group, members in groups.items():
        lines = ['# %s' % (group[:1].upper() + group[1:]), '',
                 GENERATED % ('`%s/`' % group), '',
                 'Every entry in this group, in full. Each one is written in '
                 'its own file, and that file is where it is edited.', '',
                 '| | |', '|---|---|']
        for e in members:
            lines.append('| [%s](#%s) | %s |' % (e.name, e.name, e.summary))
        lines.append('')
        for e in members:
            body = _rebase(_shift(e.text.strip('\n')),
                           os.path.dirname(e.path), commands)
            lines += ['---', '', '<a name="%s"></a>' % e.name, '', body, '']
        out[os.path.join(commands, group + '.md')] = \
            '\n'.join(lines).rstrip('\n') + '\n'
    out[os.path.join(commands, 'index.md')] = _index(root, entries)
    out[os.path.join(commands, 'groups.md')] = _groups(root, entries)
    return out


def _groups(root, entries):
    """Every name on the list that gets an entry, by the group HP files it
    under; a name with an entry links to it."""
    rows = namelist.read(_list_path(root))[0]
    by_entry = OrderedDict((e.name, e) for e in entries if e.name)
    groups = OrderedDict()
    for r in sorted((r for r in rows if r.documented),
                    key=lambda r: (r.group or '~', r.name.lower(), r.name)):
        groups.setdefault(r.group or 'ungrouped', []).append(r)
    lines = ['# Commands by group', '', GENERATED % '`docs/commands/`', '',
             'Every name that gets an entry, under the group HP files it '
             'in. A name that has its entry already links to it. The same '
             'names in alphabetical order, with what each one does: '
             '[index.md](index.md).', '']
    for group, members in groups.items():
        written = [r for r in members if r.name in by_entry]
        cells = []
        for r in members:
            e = by_entry.get(r.name)
            cells.append('[%s](%s/%s.md)' % (e.name, e.folder, e.stem) if e
                         else '`%s`' % r.name)
        lines += ['## %s' % group, '',
                  '%d name%s, %d with an entry.'
                  % (len(members), '' if len(members) == 1 else 's',
                     len(written)), '',
                  ' · '.join(cells), '']
    return '\n'.join(lines).rstrip('\n') + '\n'


def stale(root, entries):
    """Generated pages that are missing, out of date, or no longer made."""
    problems = []
    want = generated(root, entries)
    for path, text in want.items():
        if not os.path.exists(path):
            problems.append(Problem(root, path, 1, 'missing: run hpprime '
                                    'docs to generate it'))
        elif io.open(path, encoding='utf-8').read() != text:
            problems.append(Problem(root, path, 1, 'out of date: run hpprime '
                                    'docs to regenerate it'))
    commands = os.path.join(root, 'docs', 'commands')
    if os.path.isdir(commands):
        wanted = set(_key(p) for p in want)
        for name in sorted(os.listdir(commands)):
            path = os.path.join(commands, name)
            if name.endswith('.md') and _key(path) not in wanted:
                problems.append(Problem(root, path, 1, 'no folder of entries '
                                        'produces this page: delete it'))
    return problems


def build(root=ROOT, entries=None):
    """Write every generated page that differs. -> the paths written."""
    if entries is None:
        entries = load(root)[0]
    written = []
    for path, text in generated(root, entries).items():
        old = (io.open(path, encoding='utf-8').read()
               if os.path.exists(path) else None)
        if old != text:
            with io.open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            written.append(path)
    return written


def results_check(root, entries):
    """The documentation against what the Virtual Calculator answered, in
    docs/commands/results.tsv. An example whose stored answer differs from
    what its entry states is a problem for a person to settle, and so is an
    example labelled emulator with no stored answer."""
    from hpkit import examples
    results = examples.read_results(root)
    problems = []
    for e in entries:
        for ex in e.examples:
            if ex.no_value:
                continue        # a batch never runs it, so nothing is stored
            r = results.get((e.name, ex.call))
            if r is None:
                if ex.label == 'emulator':
                    problems.append(Problem(
                        root, e.path, ex.line, 'labelled emulator, but '
                        'results.tsv holds no answer for %s' % ex.call))
                continue
            stated = examples.ERROR if ex.result is None else ex.result
            number = None
            if r['type'] == '0':
                try:
                    number = float(r['answer'])
                except ValueError:
                    number = None
            if not examples.agrees(stated, r['answer'], number):
                problems.append(Problem(
                    root, e.path, ex.line, 'the emulator answers %s on %s; '
                    'the entry says %s' % (r['answer'], r['firmware'],
                                           stated)))
    return problems


def check(root=ROOT):
    """-> (problems, notes): everything wrong with the documentation, and
    the examples the interpreter could not check."""
    entries, facts, problems = load(root)
    problems += cross_check(root, entries, facts)
    problems += list_check(root, entries)
    problems += results_check(root, entries)
    p, notes, _ = run_examples(root, entries)
    problems += p
    problems += stale(root, entries)
    return problems, notes


# ---------------------------------------------------------------------- cli

USAGE = """hpprime docs [--check]

Hold the documentation to its format, and regenerate the pages made from it.

  (no option)   check the entries, then regenerate docs/commands/<group>.md
                and docs/commands/index.md from them and the list of names
  --check       change nothing; exit 1 if anything breaks the format or a
                generated page is out of date

The format is stated in docs/format.md.
"""


def cli(argv):
    if '--help' in argv or '-h' in argv:
        print(USAGE)
        return 0
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(errors='replace')
    entries, facts, problems = load(ROOT)
    if '--check' not in argv:
        if problems:
            print('not regenerating: the entries have problems')
        else:
            for path in build(ROOT, entries):
                print('wrote %s' % _rel(ROOT, path))
    problems, notes = check(ROOT)
    entries, facts, _ = load(ROOT)
    _, _, ran = run_examples(ROOT, entries)
    rows = namelist.read(_list_path(ROOT))[0]
    documented = set(r.name for r in rows if r.documented)
    for n in notes:
        print('%s (note)' % n)
    for p in problems:
        print('%s' % p)
    print('%d entries, %d facts, %d example(s) run through the interpreter; '
          '%d of the %d names on the list have an entry: %d problem(s)'
          % (len(entries), len(facts), ran,
             sum(1 for e in entries if e.name in documented), len(documented),
             len(problems)))
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(cli(sys.argv[1:]))
